require 'exception_notification/rails'
require 'exception_notification/sidekiq'

ExceptionNotification.configure do |config|
  # Ignore additional exception types.
  # ActiveRecord::RecordNotFound, Mongoid::Errors::DocumentNotFound, AbstractController::ActionNotFound and ActionController::RoutingError are already added.
  # config.ignored_exceptions += %w{ActionView::TemplateError CustomError}

  # Adds a condition to decide when an exception must be ignored or not.
  # The ignore_if method can be invoked multiple times to add extra conditions.
  # config.ignore_if do |exception, options|
  #   not Rails.env.production?
  # end

  # Ignore exceptions generated by crawlers
  # config.ignore_crawlers %w{Googlebot bingbot}

  # Notifiers =================================================================

  # Email notifier sends notifications by email.
  config.add_notifier :email, {
    email_prefix: '[ERROR] ',
    sender_address: %{"Notifier" <notifier@example.com>},
    exception_recipients: %w{max.popov@gmail.com},
    deliver_with: :deliver_now,
  }

  # config.add_notifier :slack, {
  #   webhook_url: ENV['SLACK_INCOMING_URL'],
  #   channel: ENV['SLACK_CHANNEL'],
  #   additional_parameters: {
  #     icon_url: 'https://slack.com/img/icons/app-57.png',
  #     mrkdwn: true
  #   }
  # }

  config.ignore_if do |exception, options|
    false
  end

  config.error_grouping = false #!Rails.env.test?
  # config.error_grouping_period = 1.second

  # Campfire notifier sends notifications to your Campfire room. Requires 'tinder' gem.
  # config.add_notifier :campfire, {
  #   subdomain: 'my_subdomain',
  #   token: 'my_token',
  #   room_name: 'my_room'
  # }

  # HipChat notifier sends notifications to your HipChat room. Requires 'hipchat' gem.
  # config.add_notifier :hipchat, {
  #   api_token: 'my_token',
  #   room_name: 'my_room'
  # }

  # Webhook notifier sends notifications over HTTP protocol. Requires 'httparty' gem.
  # config.add_notifier :webhook, {
  #   url: 'http://example.com:5555/hubot/path',
  #   http_method: :post
  # }
end
